name: App Continuous Integration
on:
  pull_request:
    branches:
      - main
    paths:
      - "app/**"
      - ".github/workflows/app-**.yaml"
env:
  APP_DIR: ${{ github.workspace }}/app

permissions:
  contents: read
  id-token: write
  pull-requests: write

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build Test
        id: build-test
        uses: docker/build-push-action@v6
        with:
          context: ${{ env.APP_DIR }}
          file: ${{ env.APP_DIR }}/Dockerfile
          push: false
          tags: app:latest

      - name: Comment on Pull Request
        uses: thollander/actions-comment-pull-request@v3
        if: always()
        with:
          message: |
            ```markdown
                | Step       | Status  |
                | ---------- | ------- |
                | Build Test | ${{ steps.build-test.outcome }} |
            ```
          comment-tag: "build-status"
          mode: recreate
