name: IaaC Continuous Integration
on:
  pull_request:
    branches:
      - release/*
      - main
    paths:
      - "iaac/**"
      - ".github/workflows/iaac-**.yaml"
env:
  APP_DIR: ${{ github.workspace }}/iaac
  APP_ENV: ${{ github.ref_name == 'release/production' && 'production' || github.ref_name == 'release/staging' && 'staging' || 'development' }}

permissions:
  contents: read
  id-token: write
  pull-requests: write

jobs:
  test:
    environment:
      name: ${{ github.ref_name == 'release/production' && 'production' || github.ref_name == 'release/staging' && 'staging' || 'development' }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4 # More information on this action can be found below in the 'AWS Credentials' section
        with:
          aws-region: ${{ vars.AWS_REGION }}
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "22"

      - name: install cdktf
        run: |
          npm install -g cdktf-cli

      - name: Install Dependencies
        working-directory: ${{ env.APP_DIR }}
        run: |
          npm install
          cdktf get

      - name: Build Test
        id: build-test
        run: cdktf synth
        env:
          APP_ENV: ${{ env.APP_ENV }}

      - name: Comment on Pull Request
        uses: thollander/actions-comment-pull-request@v3
        if: always()
        with:
          message: |
            ```markdown
                | Step       | Status  |
                | ---------- | ------- |
                | Build Test | ${{ steps.build-test.outcome }} |
            ```
          comment-tag: "build-status"
          mode: recreate
